name: Docker Build and Deploy

on:
  push:
    branches: [ Backy ]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: mystacr # Replace with your Azure Container Registry name
  IMAGE_NAME: mystwell-api
  AZURE_WEBAPP_NAME: mystwell-api # Replace with your Azure Web App name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          file: ./Dockerfile
          context: .
          cache-from: type=registry,ref=${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

      - name: Log in to Azure 
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Web App ACR authentication
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config container set --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group mystwellresources --container-image-name ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} --container-registry-url https://${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io --container-registry-user ${{ secrets.AZURE_REGISTRY_USERNAME }} --container-registry-password ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} 